/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '3/2/25, 3:10 AM' 
 * Generated by 'gui24002' 
 * Generated on server 'CTX-VDA-MSB-B02.GROVE.AD.UCONN.EDU' 
 * Generated on SAS platform 'X64_SRV19 WIN' 
 * Generated on SAS version '9.04.01M7P08052020' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko' 
 * Generated on web client 'http://localhost:56156/main?locale=en_US&zone=GMT-05%253A00&sutoken=%257B78F29F2C-35F4-48A5-A778-498879A038B5%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=WORK.TSPREP out=Work.preProcessedData;
	by Date;
run;

proc timeseries data=Work.preProcessedData seasonality=52 plots=(series cycles 
		corr decomp tc tcc sc);
	id Date interval=week;
	var 'Page.Loads'n / accumulate=none transform=none dif=0 sdif=0;
	decomp tc trendcycle seasonal / mode=multoradd;
run;

/* Unit root test analysis */
proc arima data=Work.preProcessedData plots=none;
	ods select StationarityTests;
	identify var='Page.Loads'n stationarity=(adf=2);
	run;
quit;

proc delete data=Work.preProcessedData;
run;